# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_testrcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_testrcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_testrcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_testrcpp_rcpparma_bothproducts`, x)
}

fun_mul <- function(A, x) {
    .Call(`_testrcpp_fun_mul`, A, x)
}

fun_dev <- function(A, x) {
    .Call(`_testrcpp_fun_dev`, A, x)
}

G_thres_cpp <- function(x, thres) {
    .Call(`_testrcpp_G_thres_cpp`, x, thres)
}

post_e_cpp <- function(l, Se_pos, Se_neg, Se_pos_other, Se_neg_other, Sc, r, s_sq, Xmat, lambda, Y_pos, Y_neg, thres) {
    .Call(`_testrcpp_post_e_cpp`, l, Se_pos, Se_neg, Se_pos_other, Se_neg_other, Sc, r, s_sq, Xmat, lambda, Y_pos, Y_neg, thres)
}

post_tau_cpp <- function(n, Se_pos, Se_neg, Sc, Xmat, Y_pos, Y_neg, alpha1, beta1, alpha2, beta2, thres) {
    .Call(`_testrcpp_post_tau_cpp`, n, Se_pos, Se_neg, Sc, Xmat, Y_pos, Y_neg, alpha1, beta1, alpha2, beta2, thres)
}

sample_c_l_cpp <- function(grids, n, l, Se_pos, Se_neg, Sc_other, r, s_sq, tau_xi_sq, Xmat, lambda, Y_pos, Y_neg, thres) {
    .Call(`_testrcpp_sample_c_l_cpp`, grids, n, l, Se_pos, Se_neg, Sc_other, r, s_sq, tau_xi_sq, Xmat, lambda, Y_pos, Y_neg, thres)
}

sample_thres_cpp <- function(grids, n, Se_pos, Se_neg, Sc, r, s_sq, tau_xi_sq, Xmat, lambda, Y_pos, Y_neg) {
    .Call(`_testrcpp_sample_thres_cpp`, grids, n, Se_pos, Se_neg, Sc, r, s_sq, tau_xi_sq, Xmat, lambda, Y_pos, Y_neg)
}

loglikelihood_cpp <- function(n, Se_pos, Se_neg, Sc, r, s_sq, Xmat, Y_pos, Y_neg, thres) {
    .Call(`_testrcpp_loglikelihood_cpp`, n, Se_pos, Se_neg, Sc, r, s_sq, Xmat, Y_pos, Y_neg, thres)
}

sample_gibbs_cpp <- function(grids, T, V, n, L, Xmat, lambda, tau_1_sq_init, tau_2_sq_init, c_init, e_pos_init, e_neg_init, Y_pos, Y_neg, alpha1, beta1, alpha2, beta2, thres_init, rinvgamma) {
    .Call(`_testrcpp_sample_gibbs_cpp`, grids, T, V, n, L, Xmat, lambda, tau_1_sq_init, tau_2_sq_init, c_init, e_pos_init, e_neg_init, Y_pos, Y_neg, alpha1, beta1, alpha2, beta2, thres_init, rinvgamma)
}

